name: Deploy Functions to Azure

on:
  workflow_dispatch:

env:
  AZURE_FNAPP_NAME: ${{ vars.APP_PREFIX }}-cosu-fn

jobs:
  build-function:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FNAPP_NAME }}'
          dotnet build ./src/ContosoSuitesVectorizationFunction/ContosoSuitesVectorizationFunction.csproj --configuration Release --output ./output
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FNAPP_NAME }}
          package: '${{ env.AZURE_FNAPP_NAME }}/output'

  
