name: Deploy Functions to Azure

on:
  workflow_dispatch:

env:
  AZURE_FNAPP_NAME: ${{ vars.APP_PREFIX }}-cosu-fn

jobs:
  build-function:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          dotnet build ./src/ContosoSuitesVectorizationFunction/ContosoSuitesVectorizationFunction.csproj --configuration Release --output ./output

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FNAPP_NAME }}
          package: './output'

  
